name: gunpoint
version: 2.0.7+2
description: "At this point God all i want is that these tests work."

homepage: https://github.com/GunPointCoders/harvest

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  meta: ^1.3.0

dev_dependencies:
  coverage: ^1.0.1
  #codecov: "^3.8.3"
  build_runner: ^2.0.6
  collection: ^1.15.0
  test: ^1.17.0
  fake_async: ^1.2.0
  lints: ^2.0.0
  mocktail: ^0.3.0
  cupertino_icons: ^1.0.2
  shared_preferences: ^2.0.13
  fluttertoast: ^8.0.9
  http: ^0.13.4
  charts_flutter: ^0.12.0
  searchfield: ^0.6.4
