version: 2.1

orbs:
  flutter: circleci/flutter@1.1.0
  orb-tools: circleci/orb-tools@10.0

parameters:
 run-integration-tests:
   description: An internal flag to prevent integration test from running before a development version has been created
   type: boolean
   default: false

jobs:
  build:
    docker:
      - image: cirrusci/flutter
    steps:
      - checkout
      - run: flutter doctor
    # fetching code from repo
Fetch-code:
  docker:
    -image:cirrus/flutter
  steps:
    -checkout
    -run:flutter doctor
workflows:
  version: 2.1
  harvest: # this is the name of our workflow
    jobs: # and here we list the jobs we are going to run.
      - build
      