version: 2.1

jobs:
  build:
    working_directory: ~/project
    docker:
      - image: cirrusci/flutter
    steps:
      - checkout
      - run: flutter main.dart
  test:
    working_directory: ~/project
    docker:
      - image: cirrusci/flutter
    steps:
      - checkout
      - run: flutter widger_test.dart
workflows:
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build

