version: 2.1
orbs:
       android: circleci/android@1.0.3
       flutter: circleci/flutter@1.0
jobs: 
  build:
   docker:
     -image: cirrusci/flutter
   steps:
     -checkout
     -flutter/install_sdk_and_pub
     -run:flutter doctor
Fetch-code:
  docker:
    -image: cirrusci/flutter
  steps:
    -checkout
    -flutter/install_sdk_and_pub
workflows:
  version: 2
  build: # this is the aname of our workflow
  jobs:# and here we list jobs we are running
   -build

install_sdk_and_pub:
        description: |
            Install Flutter SDK and your flutter packages with automated caching and best practices applied. Requires lock file.
        parameters:
            app-dir:
                default: .
                description: Path to the directory containing your pubspec.yaml file. Not needed if pubspec.yaml lives in the root.
                type: string
            cache-version:
                default: v1
                description: Change the default cache version if you need to clear the cache for any reason.
                type: string
            flutter_version:
                default: 2.2.3
                description: The target version for the Flutter SDK.
                type: string
            install-location:
                default: ~/development
                description: Install path for the Flutter binaries.
                type: string
        steps:
            - install_sdk:
                install-location: <<parameters.install-location>>
                version: <<parameters.flutter_version>>
            - install_pub:
                app-dir: <<parameters.app-dir>>
                cache-version: <<parameters.app-dir>>

