version: 2.1

executors:
  flutter:
    docker:
      - image: cirrusci/flutter
jobs:
  test:
    executor: flutter
    steps:
      - checkout
      - run:
          name: Get flutter packages
          command: flutter packages pub get
      - run: 
          name: Flutter test
          command: flutter test

  build:
    executor: flutter
    steps:
      - checkout
      - run:
          name: Build Android
          command: flutter build appbundle --debug
      - store_artifacts:
          path: build/app/outputs/bundle/debug
workflows:
  version: 2
  flutter-build:
    jobs:
      - test
      - build:
         requires:
           - test
