version: 2.1
jobs:
  build:
    docker:
      - image: cirrusci/flutter
    steps:
      - checkout
      - run: flutter doctor
      - run: flutter test test/CountFarmers_test.dart 
      - run: flutter build apk --release
      - store_artifacts:
            path: build/app/outputs/flutter-apk/app-release.apk
