version: 2
jobs:
  build:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run: flutter doctor
workflows:
  version: 2
  dart workflow: # this is the name of our workflow
    jobs: # and here we list the jobs we are going to run.
      - build
    